development:
  adapter: postgresql
  database: sportsoverload_dev
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: sportsoverload_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sportsoverload
  host: localhost
  pool: 5
  timeout: 5000
